version: '3.8'

services:
  hotel-cancellation-predictor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
