name: Model Evaluation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run docker image
        run: |
          docker compose up --build -d
          echo "Waiting for FastAPI to be ready..."
          timeout 120 bash -c 'until curl -sf http://localhost:8000/health; do sleep 3; done'

      - name: Create and evaluate models
        run:
          curl -X POST http://localhost:8000/best-model

